# Generated by Django 6.0.3 on 2026-04-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_created_by_post_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conver_in_post_content',
            new_name='cover_in_post_content',
        ),
    ]
